apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weights
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.weights.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadb
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.datadb.size }}