apiVersion: v1
kind: Service
metadata:
  name: {{ include "serge.fullname" . }}
  labels:
    {{- include "serge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: serge
      protocol: TCP
      name: http
  selector:
    {{- include "serge.selectorLabels" . | nindent 4 }}
